---
- hosts: localhost
  connection: local
  become: true

  vars:
    - color: "1;33"
    - banner: https://raw.githubusercontent.com/roghuchi/linux-template/main/banner.sh
    
  roles:
    - prompt-change
    - banner-change