---
- name: check ps1
  shell: cat ~/.bashrc | grep "export PS1"
  register: ps1_set_check

- name: add prompt color
  lineinfile:
    path: ~/.bashrc
    line: export PS1="\e[{{ color }}m[\u@\h \W]\$ \e[m"
  when: '"PS1" not in ps1_set_check.stdout'

- name: change prompt color
  lineinfile:
    path: ~/.bashrc
    state: present
    regexp: 'export PS1='
    line: 'export PS1="\e[{{ color }}m[\u@\h \W]\$ \e[m"'
  when: '"PS1" in ps1_set_check.stdout'